version: '3.8'

#using example as template
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - FLASK_APP=app
    depends_on:
      - redis

  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
    - /proc/sys/vm:/mnt/vm

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - redis-overcommit

  celery_worker:
    image: backend
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app
    depends_on:
      - redis

  flower:
    image: mher/flower:1.2
    env_file: 
        - .env
    ports: 
        - 5555:5555
    depends_on: 
        - redis